/**
 * GENERATED by scripts/generate-run.ts. Do not edit.
 *
 * The output of a real engine run over examples/ledger, with 2000
 * generated inputs per function. Every count, counterexample and obstruction
 * below was produced by running the code, not written by hand.
 *
 * Controls: clock frozen, rng seeded, network denied, imports refused.
 * Tolerances applied: none.
 */
import type { RunResult } from "@qed/ui";

export const GENERATED_RUN: RunResult = {
  "command": "qed check --base origin/main",
  "changedFunctions": 7,
  "verifiableFunctions": 4,
  "duration": "0.1s",
  "runs": [
    {
      "path": "billing/ledger.ts",
      "symbol": "computeVat",
      "verdict": {
        "state": "EQUIVALENT",
        "inputs": 2000,
        "strategy": "type-directed, corpus-seeded"
      }
    },
    {
      "path": "billing/ledger.ts",
      "symbol": "roundHalfEven",
      "verdict": {
        "state": "EQUIVALENT",
        "inputs": 2000,
        "strategy": "type-directed, corpus-seeded"
      }
    },
    {
      "path": "billing/ledger.ts",
      "symbol": "bulkRate",
      "verdict": {
        "state": "DIVERGED",
        "counterexample": {
          "input": "{ qty: 100, tier: \"gold\" }",
          "base": "1",
          "head": "0.8",
          "repro": "qed repro billing/ledger.ts bulkRate --input '[{\"qty\":100,\"tier\":\"gold\"}]'",
          "foundAt": {
            "index": 20,
            "of": 2000
          }
        }
      }
    },
    {
      "path": "billing/ledger.ts",
      "symbol": "applyDiscount",
      "verdict": {
        "state": "EQUIVALENT",
        "inputs": 2000,
        "strategy": "type-directed, corpus-seeded"
      }
    },
    {
      "path": "orders/handlers.ts",
      "symbol": "createOrderId",
      "verdict": {
        "state": "ABSTAINED",
        "obstruction": "depends on wall-clock time"
      }
    },
    {
      "path": "orders/handlers.ts",
      "symbol": "pickWinner",
      "verdict": {
        "state": "ABSTAINED",
        "obstruction": "returns a different answer for the same input"
      }
    },
    {
      "path": "orders/handlers.ts",
      "symbol": "parseConfig",
      "verdict": {
        "state": "ABSTAINED",
        "obstruction": "parameter `cfg` has no type annotation"
      }
    }
  ]
};
