/**
 * Generates every design value the rest of the monorepo is allowed to use.
 *
 * Source of truth: src/tokens.json, copied byte-for-byte from the QED design
 * system. Nothing downstream may hand-write a colour, size, radius or spacing
 * value; verify.ts gate G2 enforces that.
 *
 * Emits:
 *   dist/tokens.css  - custom properties for both themes + type-style classes
 *   dist/index.js    - typed `var(--x)` references and raw token metadata
 *   dist/index.d.ts  - the types for the above
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "dist");

type ThemeId = string;

interface ColorToken {
  name: string;
  value: string | Record<ThemeId, string>;
  usage?: string;
}
interface ScaleToken {
  name: string;
  value: string;
  usage?: string;
}
interface TypeStyle {
  name: string;
  fontSize: string;
  lineHeight: string | number;
  fontWeight: number | string;
  letterSpacing?: string;
  sample?: string;
  usage?: string;
}
interface TypeGroup {
  name: string;
  family: string;
  styles: TypeStyle[];
}
interface Tokens {
  name: string;
  version: number;
  color: { themes: { id: string; name: string }[]; tokens: ColorToken[] };
  type: {
    fonts: { family: string; file?: string; weight?: string }[];
    families: Record<string, string>;
    groups: TypeGroup[];
  };
  spacing: { tokens: ScaleToken[] };
  radius: { tokens: ScaleToken[] };
  border: { tokens: ScaleToken[] };
}

const tokens = JSON.parse(
  readFileSync(join(here, "src", "tokens.json"), "utf8"),
) as Tokens;

const themeIds = tokens.color.themes.map((t) => t.id);
const primaryTheme = themeIds[0];
if (primaryTheme === undefined) throw new Error("tokens.json: no themes");

/** A token missing a theme's value inherits the first theme's, per the system. */
function colorFor(token: ColorToken, theme: ThemeId): string {
  if (typeof token.value === "string") return token.value;
  const direct = token.value[theme];
  if (direct !== undefined) return direct;
  const fallback = token.value[primaryTheme!];
  if (fallback === undefined) {
    throw new Error(`tokens.json: ${token.name} has no value in any theme`);
  }
  return fallback;
}

const kebab = (s: string) => s.replace(/[^A-Za-z0-9]+/g, "-").toLowerCase();
const camel = (s: string) =>
  s.replace(/[-.]+([A-Za-z0-9])/g, (_, c: string) => c.toUpperCase());

// ---------------------------------------------------------------- CSS output

const decl = (name: string, value: string) => `  --${name}: ${value};`;

function themeBlock(theme: ThemeId): string {
  return tokens.color.tokens
    .map((t) => decl(t.name, colorFor(t, theme)))
    .join("\n");
}

const staticDecls: string[] = [
  ...Object.entries(tokens.type.families).map(([k, v]) =>
    decl(`font-${k}`, v),
  ),
  ...tokens.spacing.tokens.map((t) => decl(t.name, t.value)),
  ...tokens.radius.tokens.map((t) => decl(t.name, t.value)),
  ...tokens.border.tokens.map((t) => decl(t.name, t.value)),
];

const typeDecls: string[] = [];
for (const group of tokens.type.groups) {
  for (const style of group.styles) {
    const p = `type-${kebab(style.name)}`;
    typeDecls.push(decl(`${p}-family`, `var(--font-${group.family})`));
    typeDecls.push(decl(`${p}-size`, style.fontSize));
    typeDecls.push(decl(`${p}-line`, String(style.lineHeight)));
    typeDecls.push(decl(`${p}-weight`, String(style.fontWeight)));
    typeDecls.push(
      decl(`${p}-tracking`, style.letterSpacing ?? "0em"),
    );
  }
}

const typeClasses = tokens.type.groups
  .flatMap((group) =>
    group.styles.map((style) => {
      const p = `type-${kebab(style.name)}`;
      return [
        `.t-${kebab(style.name)} {`,
        `  font-family: var(--${p}-family);`,
        `  font-size: var(--${p}-size);`,
        `  line-height: var(--${p}-line);`,
        `  font-weight: var(--${p}-weight);`,
        `  letter-spacing: var(--${p}-tracking);`,
        `}`,
      ].join("\n");
    }),
  )
  .join("\n\n");

const colorScheme: Record<string, string> = { void: "dark", paper: "light" };

const css = `/* GENERATED by packages/tokens/build.ts from src/tokens.json. Do not edit. */
/* ${tokens.name} tokens v${tokens.version} - themes: ${themeIds.join(", ")} (${primaryTheme} is primary) */

:root,
[data-theme="${primaryTheme}"] {
  color-scheme: ${colorScheme[primaryTheme] ?? "dark"};
${themeBlock(primaryTheme)}
${staticDecls.join("\n")}
${typeDecls.join("\n")}
}

${themeIds
  .slice(1)
  .map(
    (theme) => `[data-theme="${theme}"] {
  color-scheme: ${colorScheme[theme] ?? "light"};
${themeBlock(theme)}
}`,
  )
  .join("\n\n")}

/* Paper exists for print, PDFs and the audit bundle (brand book, section 2). */
@media print {
  :root:not([data-theme]) {
    color-scheme: light;
${themeBlock(themeIds[1] ?? primaryTheme)}
  }
}

${typeClasses}
`;

// ----------------------------------------------------------- JS / TS output

const colorEntries = tokens.color.tokens.map(
  (t) => `  ${JSON.stringify(camel(t.name))}: "var(--${t.name})"`,
);
const scaleEntries = (list: ScaleToken[]) =>
  list.map((t) => `  ${JSON.stringify(camel(t.name))}: "var(--${t.name})"`);

const typeStyleEntries = tokens.type.groups.flatMap((g) =>
  g.styles.map(
    (s) =>
      `  ${JSON.stringify(camel(s.name))}: "t-${kebab(s.name)}"`,
  ),
);

const rawColor = JSON.stringify(
  Object.fromEntries(
    tokens.color.tokens.map((t) => [
      t.name,
      Object.fromEntries(themeIds.map((th) => [th, colorFor(t, th)])),
    ]),
  ),
  null,
  2,
);

const js = `// GENERATED by packages/tokens/build.ts. Do not edit.
export const themes = ${JSON.stringify(themeIds)};
export const primaryTheme = ${JSON.stringify(primaryTheme)};

export const color = {
${colorEntries.join(",\n")}
};

export const space = {
${scaleEntries(tokens.spacing.tokens).join(",\n")}
};

export const radius = {
${scaleEntries(tokens.radius.tokens).join(",\n")}
};

export const border = {
${scaleEntries(tokens.border.tokens).join(",\n")}
};

/** Class name per type style, e.g. typeClass.body === "t-body". */
export const typeClass = {
${typeStyleEntries.join(",\n")}
};

/** Resolved hex per colour token per theme - for tooling and contrast gates. */
export const rawColor = ${rawColor};
`;

const unionOf = (keys: string[]) =>
  keys.map((k) => JSON.stringify(k)).join(" | ");

const dts = `// GENERATED by packages/tokens/build.ts. Do not edit.
export type ThemeId = ${unionOf(themeIds)};
export type ColorTokenName = ${unionOf(tokens.color.tokens.map((t) => camel(t.name)))};
export type SpaceTokenName = ${unionOf(tokens.spacing.tokens.map((t) => camel(t.name)))};
export type RadiusTokenName = ${unionOf(tokens.radius.tokens.map((t) => camel(t.name)))};
export type BorderTokenName = ${unionOf(tokens.border.tokens.map((t) => camel(t.name)))};
export type TypeStyleName = ${unionOf(
  tokens.type.groups.flatMap((g) => g.styles.map((s) => camel(s.name))),
)};

export declare const themes: readonly ThemeId[];
export declare const primaryTheme: ThemeId;
export declare const color: Readonly<Record<ColorTokenName, string>>;
export declare const space: Readonly<Record<SpaceTokenName, string>>;
export declare const radius: Readonly<Record<RadiusTokenName, string>>;
export declare const border: Readonly<Record<BorderTokenName, string>>;
export declare const typeClass: Readonly<Record<TypeStyleName, string>>;
export declare const rawColor: Readonly<
  Record<string, Readonly<Record<ThemeId, string>>>
>;
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "tokens.css"), css, "utf8");
writeFileSync(join(outDir, "index.js"), js, "utf8");
writeFileSync(join(outDir, "index.d.ts"), dts, "utf8");

const count =
  tokens.color.tokens.length +
  tokens.spacing.tokens.length +
  tokens.radius.tokens.length +
  tokens.border.tokens.length;
process.stdout.write(
  `@qed/tokens: ${count} tokens, ${themeIds.length} themes, ` +
    `${tokens.type.groups.flatMap((g) => g.styles).length} type styles -> dist/\n`,
);
