/**
 * Turns the design system's four SVG files into one typed module the Logo
 * component renders from.
 *
 * Nothing is re-drawn and no path is retyped: every `d` and every rect comes
 * out of the file. The single edit is the ink - the files are drawn for Void
 * with a literal fill, and the component needs a token so the logo is right on
 * Paper too (assets/Logos/README.md: "On Paper, wordmark #0b0b0b and mark
 * #06824a. Single ink each"). The generator maps each file's literal fill onto
 * the token that holds that value, so the mapping cannot drift either.
 *
 * verify.ts G4 hashes the result against design-system/logo-paths.json.
 */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const logoDir = join(root, "packages/ui/src/assets/logos");
const outFile = join(root, "packages/ui/src/generated/logos.ts");

const tokens = JSON.parse(
  readFileSync(join(root, "packages/tokens/src/tokens.json"), "utf8"),
) as {
  color: {
    themes: { id: string }[];
    tokens: { name: string; value: string | Record<string, string> }[];
  };
};

const primary = tokens.color.themes[0]?.id;
if (primary === undefined) throw new Error("tokens.json: no themes");

/** literal fill in the file -> the token that holds exactly that value */
const inkByHex = new Map<string, string>();
for (const token of tokens.color.tokens) {
  const value =
    typeof token.value === "string" ? token.value : token.value[primary];
  if (value) inkByHex.set(value.toLowerCase(), token.name);
}

type Shape =
  | { kind: "path"; d: string; fillRule?: "evenodd"; ink: string }
  | {
      kind: "rect";
      x: number;
      y: number;
      width: number;
      height: number;
      ink: string;
    };

function attr(tag: string, name: string): string | undefined {
  return new RegExp(`\\s${name}="([^"]*)"`).exec(tag)?.[1];
}

function inkFor(hex: string | undefined, file: string): string {
  if (!hex) throw new Error(`${file}: a shape has no fill`);
  const ink = inkByHex.get(hex.toLowerCase());
  if (!ink) {
    throw new Error(
      `${file}: fill ${hex} matches no token - the logo and the palette have diverged`,
    );
  }
  return ink;
}

function parse(file: string, svg: string): { viewBox: string; shapes: Shape[] } {
  const viewBox = /\sviewBox="([^"]+)"/.exec(svg)?.[1];
  if (!viewBox) throw new Error(`${file}: no viewBox`);

  const shapes: Shape[] = [];
  // Track the enclosing <g>, which carries fill and fill-rule for the wordmark.
  let groupFill: string | undefined;
  let groupRule: string | undefined;

  for (const m of svg.matchAll(/<(g|path|rect)\b([^>]*)>/g)) {
    const tag = m[1];
    const body = `<x${m[2] ?? ""}>`;
    if (tag === "g") {
      groupFill = attr(body, "fill");
      groupRule = attr(body, "fill-rule");
      continue;
    }
    const fill = attr(body, "fill") ?? groupFill;
    const ink = inkFor(fill, file);
    const rule = attr(body, "fill-rule") ?? groupRule;

    if (tag === "path") {
      const d = attr(body, "d");
      if (!d) throw new Error(`${file}: a path has no d`);
      shapes.push(
        rule === "evenodd"
          ? { kind: "path", d, fillRule: "evenodd", ink }
          : { kind: "path", d, ink },
      );
    } else {
      shapes.push({
        kind: "rect",
        x: Number(attr(body, "x") ?? "0"),
        y: Number(attr(body, "y") ?? "0"),
        width: Number(attr(body, "width") ?? "0"),
        height: Number(attr(body, "height") ?? "0"),
        ink,
      });
    }
  }
  if (shapes.length === 0) throw new Error(`${file}: no shapes`);
  return { viewBox, shapes };
}

const files = readdirSync(logoDir)
  .filter((f) => f.endsWith(".svg"))
  .sort();

const entries = files.map((file) => {
  const key = file.replace(/^qed-/, "").replace(/\.svg$/, "");
  return [key, parse(file, readFileSync(join(logoDir, file), "utf8"))] as const;
});

const body = entries
  .map(([key, art]) => {
    const shapes = art.shapes
      .map((s) =>
        s.kind === "path"
          ? `      { kind: "path", d: ${JSON.stringify(s.d)}, ink: ${JSON.stringify(s.ink)}${
              s.fillRule ? `, fillRule: "evenodd"` : ""
            } },`
          : `      { kind: "rect", x: ${s.x}, y: ${s.y}, width: ${s.width}, height: ${s.height}, ink: ${JSON.stringify(s.ink)} },`,
      )
      .join("\n");
    return `  ${JSON.stringify(key)}: {
    viewBox: ${JSON.stringify(art.viewBox)},
    shapes: [
${shapes}
    ],
  },`;
  })
  .join("\n");

const out = `// GENERATED by scripts/generate-logos.ts from packages/ui/src/assets/logos/*.svg.
// Do not edit: verify.ts G4 hashes this against the design system.

export interface LogoPath {
  kind: "path";
  d: string;
  ink: string;
  fillRule?: "evenodd";
}
export interface LogoRect {
  kind: "rect";
  x: number;
  y: number;
  width: number;
  height: number;
  ink: string;
}
export type LogoShape = LogoPath | LogoRect;

export interface LogoArt {
  viewBox: string;
  shapes: readonly LogoShape[];
}

export const logoArt = {
${body}
} as const satisfies Record<string, LogoArt>;

export type LogoArtName = keyof typeof logoArt;
`;

mkdirSync(join(root, "packages/ui/src/generated"), { recursive: true });
writeFileSync(outFile, out, "utf8");
process.stdout.write(
  `generated/logos.ts: ${entries.length} assets, ${entries.reduce((n, [, a]) => n + a.shapes.length, 0)} shapes\n`,
);
