/**
 * Runs the engine over examples/ledger and writes the result the two apps
 * display.
 *
 * Until now every verdict on the website and in the console was a literal
 * someone typed. This replaces them with the output of a real run, so a
 * change to the engine shows up on the site rather than drifting away from it.
 *
 * Run: pnpm generate:run
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { runPair, type ModulePair } from "@qed/engine";

const root = process.cwd();
const read = (name: string) =>
  readFileSync(join(root, "examples/ledger", name), "utf8");

const INPUTS = 2000;

const modules: ModulePair[] = [
  {
    path: "billing/ledger.ts",
    base: read("base.ts"),
    head: read("head.ts"),
  },
  {
    path: "orders/handlers.ts",
    base: read("impure.ts"),
    head: read("impure-head.ts"),
  },
];

const started = Date.now();
const { result, details } = runPair(modules, {
  inputs: INPUTS,
  command: "qed check --base origin/main",
});
const elapsed = Date.now() - started;

const tolerances = [
  ...new Set([...details.values()].flatMap((d) => d.tolerancesApplied)),
];

const header = `/**
 * GENERATED by scripts/generate-run.ts. Do not edit.
 *
 * The output of a real engine run over examples/ledger, with ${INPUTS}
 * generated inputs per function. Every count, counterexample and obstruction
 * below was produced by running the code, not written by hand.
 *
 * Controls: clock frozen, rng seeded, network denied, imports refused.
 * Tolerances applied: ${tolerances.length > 0 ? tolerances.join("; ") : "none"}.
 */
import type { RunResult } from "@qed/ui";
`;

const body = `
export const GENERATED_RUN: RunResult = ${JSON.stringify(
  { ...result, duration: `${(elapsed / 1000).toFixed(1)}s` },
  null,
  2,
)};
`;

for (const target of [
  "apps/web/src/run.generated.ts",
  "apps/console/src/run.generated.ts",
]) {
  writeFileSync(join(root, target), `${header}${body}`, "utf8");
}

const counts = result.runs.reduce<Record<string, number>>((acc, run) => {
  acc[run.verdict.state] = (acc[run.verdict.state] ?? 0) + 1;
  return acc;
}, {});

process.stdout.write(
  `generated run: ${result.runs.length} functions - ` +
    Object.entries(counts)
      .map(([state, n]) => `${n} ${state}`)
      .join(", ") +
    `\n`,
);
