/**
 * Measures the two self-hosted families against the fallback a browser shows
 * while they load, and writes the @font-face overrides that stop the swap
 * moving the page.
 *
 * Nothing here is estimated: the numbers come from the real faces, rendered,
 * and the script re-measures afterwards and fails if any line still moves by
 * more than 1%.
 *
 * Run: pnpm measure:fonts (needs the gallery server, which it starts itself).
 */
import { spawn } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { chromium, type Page } from "@playwright/test";

const root = process.cwd();
const OUT = join(root, "packages/ui/src/styles/fallback-metrics.generated.css");
const URL = "http://localhost:4313/";

/** The face the browser actually falls back to, per the token's own chain. */
const FAMILIES = [
  {
    real: "Instrument Sans",
    fallbackLocal: "Arial",
    name: "Instrument Sans Fallback",
    token: "--font-text",
    alsoToken: "--font-display",
  },
  {
    real: "Martian Mono",
    fallbackLocal: "Courier New",
    name: "Martian Mono Fallback",
    token: "--font-data",
  },
] as const;

/** Long enough that one wide glyph cannot dominate the ratio. */
const SAMPLE =
  "Equivalent on 18,402 generated inputs - billing/tax.go computeVat 0.85 head 0.8 ABSTAINED";

interface Metrics {
  width: number;
  ascent: number;
  descent: number;
}

async function measure(
  page: Page,
  family: string,
  sample: string,
): Promise<Metrics> {
  return page.evaluate(
    ({ family: f, sample: s }) => {
      const canvas = document.createElement("canvas");
      const context = canvas.getContext("2d");
      if (!context) throw new Error("no 2d context");
      const size = 100;
      context.font = `${size}px "${f}"`;
      const m = context.measureText(s);
      return {
        width: m.width,
        ascent: m.fontBoundingBoxAscent / size,
        descent: m.fontBoundingBoxDescent / size,
      };
    },
    { family, sample },
  );
}

const pct = (n: number) => `${(n * 100).toFixed(2)}%`;

async function main(): Promise<void> {
  const server = spawn(
    "pnpm",
    ["exec", "vite", "--config", "tests/gallery/vite.config.ts"],
    { cwd: root, stdio: "ignore", shell: process.platform === "win32" },
  );

  const browser = await chromium.launch();
  const page = await browser.newPage();

  try {
    for (let attempt = 0; attempt < 30; attempt++) {
      try {
        await page.goto(URL, { timeout: 2000 });
        break;
      } catch {
        await new Promise((r) => setTimeout(r, 500));
      }
    }
    await page.evaluate(() => document.fonts.ready);

    const blocks: string[] = [];
    const report: string[] = [];

    for (const family of FAMILIES) {
      const real = await measure(page, family.real, SAMPLE);
      const fallback = await measure(page, family.fallbackLocal, SAMPLE);
      if (real.width === 0 || fallback.width === 0) {
        throw new Error(`could not measure ${family.real} against ${family.fallbackLocal}`);
      }

      const sizeAdjust = real.width / fallback.width;
      // Overrides are expressed against the adjusted em, so divide them back.
      const ascent = real.ascent / sizeAdjust;
      const descent = real.descent / sizeAdjust;

      blocks.push(
        [
          `@font-face {`,
          `  font-family: "${family.name}";`,
          `  src: local("${family.fallbackLocal}");`,
          `  size-adjust: ${pct(sizeAdjust)};`,
          `  ascent-override: ${pct(ascent)};`,
          `  descent-override: ${pct(descent)};`,
          `  line-gap-override: 0%;`,
          `}`,
        ].join("\n"),
      );
      report.push(
        `${family.real}: size-adjust ${pct(sizeAdjust)} over ${family.fallbackLocal}`,
      );
    }

    const tokenOverrides = [
      `:root,`,
      `[data-theme] {`,
      `  --font-display: "Instrument Sans", "Instrument Sans Fallback", "Helvetica Neue", Arial, sans-serif;`,
      `  --font-text: "Instrument Sans", "Instrument Sans Fallback", "Helvetica Neue", Arial, sans-serif;`,
      `  --font-data: "Martian Mono", "Martian Mono Fallback", "SFMono-Regular", Menlo, monospace;`,
      `}`,
    ].join("\n");

    const css = `/*
 * GENERATED by scripts/measure-fonts.ts. Do not edit.
 *
 * Metric-matched fallbacks: while the woff2 files load, the browser shows a
 * local face scaled to the same advance width and the same box, so the swap
 * does not move a line. The families below re-declare the token chains from
 * tokens.json with the adjusted face inserted after the real one.
 *
 * ${report.join("\n * ")}
 */

${blocks.join("\n\n")}

${tokenOverrides}
`;

    writeFileSync(OUT, css, "utf8");

    // Re-measure with the generated faces in place.
    await page.addStyleTag({ content: css });
    await page.evaluate(() => document.fonts.ready);

    let worst = 0;
    for (const family of FAMILIES) {
      const real = await measure(page, family.real, SAMPLE);
      const adjusted = await measure(page, family.name, SAMPLE);
      const delta = Math.abs(adjusted.width - real.width) / real.width;
      worst = Math.max(worst, delta);
      process.stdout.write(
        `${family.real}: residual width shift ${(delta * 100).toFixed(3)}%\n`,
      );
    }

    process.stdout.write(`${OUT}\n`);
    if (worst > 0.01) {
      process.stdout.write(
        `\nfallback still shifts layout by ${(worst * 100).toFixed(2)}% - over the 1% budget\n`,
      );
      process.exitCode = 1;
    }
  } finally {
    await browser.close();
    server.kill();
  }
}

await main();
